version: "3.9"

services:

  pdns_db:
    image: postgres:13
    container_name: pdns_db
    hostname: pdns_db
    restart: always
    networks:
      - pdns_db_net
    environment:
      POSTGRES_DB: pdns
      POSTGRES_USER: pdns
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
    volumes:
      - db:/var/lib/postgresql/data
      - ./authoritative/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db_passwd
    user: postgres:postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pdns" ]
      interval: 10s
      timeout: 5s
      retries: 10
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  pdns_authoritative:
    build: authoritative
    image: powerdns:authoritative
    container_name: pdns_authoritative
    hostname: pdns_authoritative
    restart: always
    networks:
      pdns_db_net:
      pdns_web_net:
      pdns_auth_net:
        ipv4_address: "172.26.0.122"
    depends_on:
      pdns_db:
        condition: service_healthy
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  pdns_admin_db:
    image: postgres:13
    container_name: pdns_admin_db
    hostname: pdns_admin_db
    restart: always
    networks:
      - pdns_admin_db_net
    environment:
      POSTGRES_DB: pdns_admin
      POSTGRES_USER: pdns_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/admin_db_password
    volumes:
      - db_admin:/var/lib/postgresql/data
    secrets:
      - admin_db_password
    user: postgres:postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pdns_admin" ]
      interval: 10s
      timeout: 5s
      retries: 10
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  pdns_admin:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: pdns_admin
    hostname: pdns_admin
    restart: always
    networks:
      - pdns_admin_db_net
      - pdns_web_net
      - nginx_admin_net
    environment:
      - SECRET_KEY_FILE=/run/secrets/pdns_admin_secret_key
      - SQLALCHEMY_DATABASE_URI_FILE=/run/secrets/db_uri
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=1
    secrets:
      - pdns_admin_secret_key
      - db_uri
    depends_on:
      pdns_admin_db:
        condition: service_healthy
      pdns_authoritative:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges

  pdns_recursor:
    build: recursor
    image: powerdns:recursor
    container_name: pdns_recursor
    hostname: pdns_recursor
    restart: always
    networks:
      pdns_rec_net:
        ipv4_address: "172.26.0.114"
    depends_on:
      pdns_authoritative:
        condition: service_healthy
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  pdns_forwarder:
    build: forwarder
    image: powerdns:forwarder
    container_name: pdns_forwarder
    hostname: pdns_forwarder
    restart: always
    networks:
      pdns_auth_net:
      pdns_rec_net:
      hole_net:
        ipv4_address: "172.26.0.130"
    depends_on:
      pdns_authoritative:
        condition: service_healthy
      pdns_recursor:
        condition: service_healthy
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: pihole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - hole_net
      - nginx_pihole_net
    environment:
      - TZ=Europe/Amsterdam
      - PIHOLE_DNS_=172.26.0.130
      - DNSMASQ_LISTENING=all
    volumes:
      - pihole:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    depends_on:
      pdns_forwarder:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - SETFCAP
    security_opt:
      - no-new-privileges

  nginx:
    build:
      context: nginx
      args:
        ADMIN_HOSTNAME: pdns.local.intra
        PIHOLE_HOSTNAME: pihole.local.intra
    image: powerhole:nginx
    container_name: powerhole_nginx
    restart: always
    ports:
      - "80:8080"
      - "443:44380"
    networks:
      - nginx_admin_net
      - nginx_pihole_net
    secrets:
      - source: certificate
        target: /srv/certificates/fullchain.pem
      - source: private_key
        target: /srv/certificates/privkey.pem
      - source: dh_params
        target: /srv/certificates/dhparams.pem
    depends_on:
      pdns_admin:
        condition: service_healthy
      pihole:
        condition: service_healthy
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges

volumes:
  db:
  db_admin:
  pihole:
  dnsmasq:

secrets:

  db_passwd:
    file: ./secrets/db_password.txt

  pdns_admin_secret_key:
    file: ./secrets/pdns_admin_secret_key.txt

  admin_db_password:
    file: ./secrets/admin_db_password.txt

  db_uri:
    file: ./secrets/db_uri.txt

  certificate:
    file: ./secrets/ssl/fullchain.pem

  private_key:
    file: ./secrets/ssl/privkey.pem

  dh_params:
    file: ./secrets/ssl/dhparams.pem

networks:

  pdns_db_net:
    name: pdns_db_net
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.88/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-pdns_db

  pdns_admin_db_net:
    name: pdns_admin_db_net
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.96/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-pdns_admin

  pdns_web_net:
    name: pdns_web_net
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.104/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-pdns_web

  pdns_rec_net:
    name: pdns_rec_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.112/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-pdns_rec

  pdns_auth_net:
    name: pdns_auth_net
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.120/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-pdns_auth

  hole_net:
    name: hole_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.128/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-hole

  nginx_admin_net:
    name: nginx_admin_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.136/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-ng_admin

  nginx_pihole_net:
    name: nginx_pihole_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.144/29"
    driver_opts:
      com.docker.network.bridge.name: dbr-ng_pihole
